/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const Sim: core.schemas.ObjectSchema<serializers.Sim.Raw, GigsApi.Sim> = core.schemas.object({
  object: core.schemas.lazy(async () => (await import("../..")).SimObject),
  id: core.schemas.string(),
  iccid: core.schemas.string(),
  provider: core.schemas.string(),
  status: core.schemas.lazy(async () => (await import("../..")).SimStatus),
  type: core.schemas.lazy(async () => (await import("../..")).SimTypes),
  createdAt: core.schemas.date(),
});

export declare namespace Sim {
  interface Raw {
    object: serializers.SimObject.Raw;
    id: string;
    iccid: string;
    provider: string;
    status: serializers.SimStatus.Raw;
    type: serializers.SimTypes.Raw;
    createdAt: string;
  }
}
