/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsGigsCoreApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const SimId: core.schemas.Schema<serializers.SimId.Raw, GigsGigsCoreApi.SimId> = core.schemas.string();

export declare namespace SimId {
  type Raw = string;
}
