/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const SimObject: core.schemas.Schema<serializers.SimObject.Raw, GigsApi.SimObject> = core.schemas.enum_(["sim"]);

export declare namespace SimObject {
  type Raw = "sim";
}
