/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsGigsCoreApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const SimObject: core.schemas.Schema<serializers.SimObject.Raw, GigsGigsCoreApi.SimObject> = core.schemas.enum_([
  "sim",
]);

export declare namespace SimObject {
  type Raw = "sim";
}
