/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const SimStatus: core.schemas.Schema<serializers.SimStatus.Raw, GigsApi.SimStatus> = core.schemas.enum_([
  "inactive",
  "active",
  "retired",
]);

export declare namespace SimStatus {
  type Raw = "inactive" | "active" | "retired";
}
