/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsGigsCoreApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const SimTypes: core.schemas.Schema<serializers.SimTypes.Raw, GigsGigsCoreApi.SimTypes> = core.schemas.enum_([
  "eSIM",
  "pSIM",
]);

export declare namespace SimTypes {
  type Raw = "eSIM" | "pSIM";
}
