/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const Device: core.schemas.ObjectSchema<serializers.Device.Raw, GigsApi.Device> = core.schemas.object({
  object: core.schemas.string(),
  id: core.schemas.lazy(async () => (await import("../..")).DeviceId),
  brand: core.schemas.string(),
  name: core.schemas.string(),
  simTypes: core.schemas.list(core.schemas.lazy(async () => (await import("../..")).SimTypes)),
  type: core.schemas.lazy(async () => (await import("../..")).DeviceModelType),
});

export declare namespace Device {
  interface Raw {
    object: string;
    id: serializers.DeviceId.Raw;
    brand: string;
    name: string;
    simTypes: serializers.SimTypes.Raw[];
    type: serializers.DeviceModelType.Raw;
  }
}
