/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const CoverageObject: core.schemas.Schema<serializers.CoverageObject.Raw, GigsApi.CoverageObject> =
  core.schemas.enum_(["coverage"]);

export declare namespace CoverageObject {
  type Raw = "coverage";
}
