/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsGigsCoreApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const DataUnit: core.schemas.Schema<serializers.DataUnit.Raw, GigsGigsCoreApi.DataUnit> = core.schemas.enum_([
  "byte",
]);

export declare namespace DataUnit {
  type Raw = "byte";
}
