/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsGigsCoreApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const PlanRequirementsUserBirthday: core.schemas.Schema<
  serializers.PlanRequirementsUserBirthday.Raw,
  GigsGigsCoreApi.PlanRequirementsUserBirthday
> = core.schemas.enum_(["none", "present", "verified"]);

export declare namespace PlanRequirementsUserBirthday {
  type Raw = "none" | "present" | "verified";
}
