/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const PlanId: core.schemas.Schema<serializers.PlanId.Raw, GigsApi.PlanId> = core.schemas.string();

export declare namespace PlanId {
  type Raw = string;
}
