/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const PlanObject: core.schemas.Schema<serializers.PlanObject.Raw, GigsApi.PlanObject> = core.schemas.enum_([
  "plan",
]);

export declare namespace PlanObject {
  type Raw = "plan";
}
