/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const PlanRequirementsDevice: core.schemas.Schema<
  serializers.PlanRequirementsDevice.Raw,
  GigsApi.PlanRequirementsDevice
> = core.schemas.enum_(["none", "present", "verified"]);

export declare namespace PlanRequirementsDevice {
  type Raw = "none" | "present" | "verified";
}
