/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const PlanRequirementsUserFullName: core.schemas.Schema<
  serializers.PlanRequirementsUserFullName.Raw,
  GigsApi.PlanRequirementsUserFullName
> = core.schemas.enum_(["none", "present", "verified"]);

export declare namespace PlanRequirementsUserFullName {
  type Raw = "none" | "present" | "verified";
}
