/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsGigsCoreApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const PlanObject: core.schemas.Schema<serializers.PlanObject.Raw, GigsGigsCoreApi.PlanObject> =
  core.schemas.enum_(["plan"]);

export declare namespace PlanObject {
  type Raw = "plan";
}
