/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const PlanStatus: core.schemas.Schema<serializers.PlanStatus.Raw, GigsApi.PlanStatus> = core.schemas.enum_([
  "available",
  "archived",
  "pending",
  "draft",
]);

export declare namespace PlanStatus {
  type Raw = "available" | "archived" | "pending" | "draft";
}
