/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const Plan: core.schemas.ObjectSchema<serializers.Plan.Raw, GigsApi.Plan> = core.schemas.object({
  object: core.schemas.string(),
  id: core.schemas.lazy(async () => (await import("../..")).PlanId),
});

export declare namespace Plan {
  interface Raw {
    object: string;
    id: serializers.PlanId.Raw;
  }
}
