/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsGigsCoreApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const ValidityUnit: core.schemas.Schema<serializers.ValidityUnit.Raw, GigsGigsCoreApi.ValidityUnit> =
  core.schemas.enum_(["day", "month"]);

export declare namespace ValidityUnit {
  type Raw = "day" | "month";
}
