/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsGigsCoreApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const VoiceUnit: core.schemas.Schema<serializers.VoiceUnit.Raw, GigsGigsCoreApi.VoiceUnit> = core.schemas.enum_([
  "second",
]);

export declare namespace VoiceUnit {
  type Raw = "second";
}
