/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../environments";
import * as core from "../../../core";
import { GigsGigsCoreApi } from "@fern-api/gigs";
import urlJoin from "url-join";
import * as serializers from "../../../serialization";

export declare namespace Client {
  interface Options {
    environment?: environments.Environment | string;
    token?: core.Supplier<core.BearerToken>;
  }
}

export class Client {
  constructor(private readonly options: Client.Options) {}

  public async list(
    project: string,
    request?: GigsGigsCoreApi.PlanListRequest
  ): Promise<GigsGigsCoreApi.plans.list.Response> {
    const _queryParams = new URLSearchParams();
    if (request?.after != null) {
      _queryParams.append("after", request?.after);
    }

    if (request?.before != null) {
      _queryParams.append("before", request?.before);
    }

    if (request?.limit != null) {
      _queryParams.append("limit", request?.limit.toString());
    }

    if (request?.plan != null) {
      _queryParams.append("plan", request?.plan);
    }

    if (request?.sim != null) {
      _queryParams.append("sim", request?.sim);
    }

    if (request?.status != null) {
      _queryParams.append("status", request?.status);
    }

    if (request?.user != null) {
      _queryParams.append("user", request?.user);
    }

    const _response = await core.fetcher({
      url: urlJoin(this.options.environment ?? environments.Environment.Production, `/projects/${project}/plans/`),
      method: "GET",
      headers: {
        Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
      },
      queryParameters: _queryParams,
    });
    if (_response.ok) {
      return {
        ok: true,
        body: await serializers.plans.list.Response.parse(_response.body as serializers.plans.list.Response.Raw),
      };
    }

    return {
      ok: false,
      error: GigsGigsCoreApi.plans.list.Error._unknown(_response.error),
    };
  }

  public async archive(project: string, id: GigsGigsCoreApi.PlanId): Promise<GigsGigsCoreApi.plans.archive.Response> {
    const _response = await core.fetcher({
      url: urlJoin(
        this.options.environment ?? environments.Environment.Production,
        `/projects/${project}/plans/${id}/archive`
      ),
      method: "GET",
      headers: {
        Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
      },
    });
    if (_response.ok) {
      return {
        ok: true,
        body: await serializers.plans.archive.Response.parse(_response.body as serializers.plans.archive.Response.Raw),
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 404:
          return {
            ok: false,
            error: GigsGigsCoreApi.plans.archive.Error.doesNotExist(
              await serializers.DoesNotExist.parse(_response.error.body as serializers.DoesNotExist.Raw)
            ),
          };
      }
    }

    return {
      ok: false,
      error: GigsGigsCoreApi.plans.archive.Error._unknown(_response.error),
    };
  }
}
