/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { GigsApi } from "@fern-api/gigs";
import * as core from "../../../core";

export type Response = core.APIResponse<GigsApi.PlanList, GigsApi.plans.list.Error>;
export type Error = GigsApi.plans.list.Error._Unknown;

export declare namespace Error {
  interface _Unknown extends _Utils {
    statusCode: void;
    content: core.Fetcher.Error;
  }

  interface _Utils {
    _visit: <_Result>(visitor: GigsApi.plans.list.Error._Visitor<_Result>) => _Result;
  }

  interface _Visitor<_Result> {
    _other: (value: core.Fetcher.Error) => _Result;
  }
}

export const Error = {
  _unknown: (fetcherError: core.Fetcher.Error): GigsApi.plans.list.Error._Unknown => {
    const valueWithoutVisit = fetcherError as unknown as Omit<GigsApi.plans.list.Error._Unknown, "_visit">;
    return core.addNonEnumerableProperty(valueWithoutVisit, "_visit", function <
      _Result
    >(this: GigsApi.plans.list.Error._Unknown, visitor: GigsApi.plans.list.Error._Visitor<_Result>) {
      return GigsApi.plans.list.Error._visit(this, visitor);
    });
  },

  _visit: <_Result>(value: GigsApi.plans.list.Error, visitor: GigsApi.plans.list.Error._Visitor<_Result>): _Result => {
    switch (value.statusCode) {
      default:
        return visitor._other(value as any);
    }
  },
} as const;
