/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { GigsGigsCoreApi } from "@fern-api/gigs";

/**
 * The requested resource doesn't exist.
 */
export type DoesNotExist = GigsGigsCoreApi.DoesNotExistBody;
