/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { GigsApi } from "@fern-api/gigs";

/**
 * The request can't be processed, often due to an invalid parameter or incompatible system state.
 */
export type InvalidIccid = GigsApi.InvalidIccidBody;
