/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { GigsApi } from "@fern-api/gigs";

export interface DoesNotExistBody {
  /** Type of object is always `error`. */
  object: string;
  /** A machine-readable description of the error. */
  code?: string;
  /** Optional array containing specific information for the current error.Show all... */
  details?: GigsApi.PropertyErrorDetail[];
  /** An optional list of URLs providing further information to resolve the error. */
  documentation?: string[];
  /** An optional explanation how to resolve the error. */
  hint?: string;
  /** A human readable description of the error. */
  message: string;
  /** The type of error returned. */
  type: string;
}
