/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { GigsApi } from "@fern-api/gigs";

export interface InvalidIccidBody {
  /** Type of object is always `error`. */
  object: GigsApi.InvalidIccidBodyObject;
  /** A machine-readable description of the error. */
  code?: string;
  /** Optional array containing specific information for the current error. */
  details?: GigsApi.PropertyErrorDetail[];
  /** An optional list of URLs providing further information to resolve the error. */
  documentation?: string[];
  /** An optional explanation how to resolve the error. */
  hint?: string;
  /** A human readable description of the error. */
  message: string;
  /** The type of [error](https://developers.gigs.com/docs/api/ZG9jOjExMTYzMDU0-error-handling) returned. */
  type: string;
}
