/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PropertyErrorDetailObject = "propertyErrorDetail";

export const PropertyErrorDetailObject = {
  PropertyErrorDetail: "propertyErrorDetail",
} as const;
