/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { GigsApi } from "@fern-api/gigs";

export interface PropertyErrorDetail {
  /** Type of object is always `propertyErrorDetail`. */
  object: GigsApi.PropertyErrorDetailObject;
  /** A machine-readable description of the error. */
  code: string;
  /** A human readable description of the error. */
  message: string;
  /** Name of the property associated with the error. */
  property: string;
  /** Suggested alternative value for the field. */
  suggestion?: string;
}
