/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     GigsGigsCoreApi.CoverageObject.Coverage
 */
export type CoverageObject = "coverage";

export const CoverageObject = {
  Coverage: "coverage",
} as const;
