/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { GigsGigsCoreApi } from "@fern-api/gigs";

export interface PlanRequirements {
  /** The address requirements that must be fulfilled before a user may purchase a subscription. */
  address: GigsGigsCoreApi.PlanRequirementsAddress;
  /** The device requirements that must be fulfilled before a user may purchase a subscription. */
  device: GigsGigsCoreApi.PlanRequirementsDevice;
  /** The user birthday requirements that must be fulfilled before a user may purchase a subscription. */
  userBirthday: GigsGigsCoreApi.PlanRequirementsUserBirthday;
  /** The user full name requirements that must be fulfilled before a user may purchase a subscription. */
  userFullName: GigsGigsCoreApi.PlanRequirementsUserFullName;
}
