/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     GigsGigsCoreApi.PlanListObject.List
 */
export type PlanListObject = "list";

export const PlanListObject = {
  List: "list",
} as const;
