/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PlanStatus = "available" | "archived" | "pending" | "draft";

export const PlanStatus = {
  Available: "available",
  Archived: "archived",
  Pending: "pending",
  Draft: "draft",
} as const;
