/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PlanRequirementsDevice = "none" | "present" | "verified";

export const PlanRequirementsDevice = {
  None: "none",
  Present: "present",
  Verified: "verified",
} as const;
