/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     GigsGigsCoreApi.PlanObject.Plan
 */
export type PlanObject = "plan";

export const PlanObject = {
  Plan: "plan",
} as const;
