/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { GigsApi } from "@fern-api/gigs";

export interface PlanRequirements {
  /** The address requirements that must be fulfilled before a user may purchase a subscription. */
  address: GigsApi.PlanRequirementsAddress;
  /** The device requirements that must be fulfilled before a user may purchase a subscription. */
  device: GigsApi.PlanRequirementsDevice;
  /** The user birthday requirements that must be fulfilled before a user may purchase a subscription. */
  userBirthday: GigsApi.PlanRequirementsUserBirthday;
  /** The user full name requirements that must be fulfilled before a user may purchase a subscription. */
  userFullName: GigsApi.PlanRequirementsUserFullName;
}
