/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { GigsApi } from "@fern-api/gigs";

export interface Plan {
  /** Type of object is always `plan`. */
  object: string;
  /** The unique identifier for the plan. */
  id: GigsApi.PlanId;
}
