/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { GigsApi } from "@fern-api/gigs";

export interface Validity {
  /** The minimum number of subscription periods that the plan must be renewed. `>= 0` */
  minimumPeriods: number;
  /** The validity type of this plan. */
  type: GigsApi.ValidityType;
  /** The time unit of the subscription period. */
  unit: GigsApi.ValidityUnit;
  /** The amount of units (specified in the `unit` property) in each subscription period. `>= 1` */
  value: number;
}
