/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ValidityType = "oneTime" | "recurring";

export const ValidityType = {
  OneTime: "oneTime",
  Recurring: "recurring",
} as const;
