/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../environments";
import * as core from "../../../core";
import { GigsApi } from "@fern-api/gigs";
import urlJoin from "url-join";
import * as serializers from "../../../serialization";

export declare namespace Client {
  interface Options {
    environment?: environments.Environment | string;
    token?: core.Supplier<core.BearerToken>;
  }
}

export class Client {
  constructor(private readonly options: Client.Options) {}

  public async create(
    project: GigsApi.ProjectId,
    request: GigsApi.CreateSubscriptionRequest
  ): Promise<GigsApi.subscriptions.create.Response> {
    const _response = await core.fetcher({
      url: urlJoin(
        this.options.environment ?? environments.Environment.Production,
        `/projects/${project}//subscriptions`
      ),
      method: "POST",
      headers: {
        Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
      },
      body: await serializers.subscriptions.create.Request.json({
        plan: request.plan,
        sim: request.sim,
        userAddress: request.userAddress,
        user: request.user,
        porting: request.porting,
      }),
    });
    if (_response.ok) {
      return {
        ok: true,
        body: await serializers.subscriptions.create.Response.parse(
          _response.body as serializers.subscriptions.create.Response.Raw
        ),
      };
    }

    return {
      ok: false,
      error: GigsApi.subscriptions.create.Error._unknown(_response.error),
    };
  }

  public async listAll(
    project: GigsApi.ProjectId,
    request?: GigsApi.ListAllSubscriptionsRequest
  ): Promise<GigsApi.subscriptions.listAll.Response> {
    const _queryParams = new URLSearchParams();
    if (request?.after != null) {
      _queryParams.append("after", request?.after);
    }

    if (request?.before != null) {
      _queryParams.append("before", request?.before);
    }

    if (request?.limit != null) {
      _queryParams.append("limit", request?.limit.toString());
    }

    if (request?.plan != null) {
      _queryParams.append("plan", request?.plan);
    }

    if (request?.sim != null) {
      _queryParams.append("sim", request?.sim);
    }

    if (request?.status != null) {
      _queryParams.append("status", request?.status);
    }

    if (request?.user != null) {
      _queryParams.append("user", request?.user);
    }

    const _response = await core.fetcher({
      url: urlJoin(
        this.options.environment ?? environments.Environment.Production,
        `/projects/${project}//subscriptions`
      ),
      method: "GET",
      headers: {
        Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
      },
      queryParameters: _queryParams,
    });
    if (_response.ok) {
      return {
        ok: true,
        body: await serializers.subscriptions.listAll.Response.parse(
          _response.body as serializers.subscriptions.listAll.Response.Raw
        ),
      };
    }

    return {
      ok: false,
      error: GigsApi.subscriptions.listAll.Error._unknown(_response.error),
    };
  }
}
