/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const User: core.schemas.ObjectSchema<serializers.User.Raw, GigsApi.User> = core.schemas.object({
  object: core.schemas.lazy(async () => (await import("../..")).UserObject),
  id: core.schemas.string(),
  birthday: core.schemas.string(),
  email: core.schemas.string(),
  emailVerified: core.schemas.boolean(),
  fullName: core.schemas.string(),
  preferredLocale: core.schemas.string(),
  createdAt: core.schemas.date(),
});

export declare namespace User {
  interface Raw {
    object: serializers.UserObject.Raw;
    id: string;
    birthday: string;
    email: string;
    emailVerified: boolean;
    fullName: string;
    preferredLocale: string;
    createdAt: string;
  }
}
