/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { GigsGigsCoreApi } from "@fern-api/gigs";

export interface CreateUserRequest {
  object: GigsGigsCoreApi.UserObject;
  birthday: string;
  email: string;
  fullName: string;
  preferredLocale: string;
}
