/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { GigsApi } from "@fern-api/gigs";

export interface PlanListRequest {
  /**
   * A cursor for use in pagination. The `after` parameter takes an object ID that defines the position in the list, only items immediately following the item with that ID will be returned.
   */
  after?: string;
  /**
   * A cursor for use in pagination. The `before` parameter takes an object ID that defines the position in the list, only items immediately preceding the item with that ID will be returned.
   */
  before?: string;
  /**
   * The limit of items to be returned in the list, between 0 and 200. `>= 0` `<= 200`. Default is `10`.
   */
  limit?: number;
  /**
   * The unique identifier for the plan to be filtered by.
   */
  plan?: GigsApi.PlanId;
  /**
   * The unique identifier for the sim to be filtered by.
   */
  sim?: GigsApi.SimId;
  /**
   * The status to filter the plans by. Only available plans are returned by default.
   */
  status?: GigsApi.PlanStatus;
  /**
   * The unique identifier for the user to be filtered by.
   */
  user?: string;
}
