/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const Request: core.schemas.Schema<serializers.users.create.Request.Raw, GigsApi.CreateUserRequest> =
  core.schemas.object({
    object: core.schemas.lazy(async () => (await import("../..")).UserObject),
    birthday: core.schemas.string(),
    email: core.schemas.string(),
    fullName: core.schemas.string(),
    preferredLocale: core.schemas.string(),
  });

export declare namespace Request {
  interface Raw {
    object: serializers.UserObject.Raw;
    birthday: string;
    email: string;
    fullName: string;
    preferredLocale: string;
  }
}

export const Response: core.schemas.Schema<serializers.users.create.Response.Raw, GigsApi.User> =
  core.schemas.lazyObject(async () => (await import("../..")).User);

export declare namespace Response {
  type Raw = serializers.User.Raw;
}
