/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const DoesNotExistBody: core.schemas.ObjectSchema<serializers.DoesNotExistBody.Raw, GigsApi.DoesNotExistBody> =
  core.schemas.object({
    object: core.schemas.string(),
    code: core.schemas.string().optional(),
    details: core.schemas
      .list(core.schemas.lazyObject(async () => (await import("../..")).PropertyErrorDetail))
      .optional(),
    documentation: core.schemas.list(core.schemas.string()).optional(),
    hint: core.schemas.string().optional(),
    message: core.schemas.string(),
    type: core.schemas.string(),
  });

export declare namespace DoesNotExistBody {
  interface Raw {
    object: string;
    code?: string | null;
    details?: serializers.PropertyErrorDetail.Raw[] | null;
    documentation?: string[] | null;
    hint?: string | null;
    message: string;
    type: string;
  }
}
