/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const InvalidIccidBodyObject: core.schemas.Schema<
  serializers.InvalidIccidBodyObject.Raw,
  GigsApi.InvalidIccidBodyObject
> = core.schemas.enum_(["error"]);

export declare namespace InvalidIccidBodyObject {
  type Raw = "error";
}
