/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const PropertyErrorDetail: core.schemas.ObjectSchema<
  serializers.PropertyErrorDetail.Raw,
  GigsApi.PropertyErrorDetail
> = core.schemas.object({
  object: core.schemas.lazy(async () => (await import("../..")).PropertyErrorDetailObject),
  code: core.schemas.string(),
  message: core.schemas.string(),
  property: core.schemas.string(),
  suggestion: core.schemas.string().optional(),
});

export declare namespace PropertyErrorDetail {
  interface Raw {
    object: serializers.PropertyErrorDetailObject.Raw;
    code: string;
    message: string;
    property: string;
    suggestion?: string | null;
  }
}
