/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateSubscriptionRequest {
  plan: string;
  sim?: string;
  userAddress?: string;
  user: string;
  porting?: string;
}
