/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { GigsApi } from "@fern-api/gigs";

export interface ListAllSubscriptionsRequest {
  /**
   * A cursor for use in pagination. The `after` parameter takes an object ID that defines the position in the list, only items immediately following the item with that ID will be returned.
   */
  after?: string;
  /**
   * A cursor for use in pagination. The `before` parameter takes an object ID that defines the position in the list, only items immediately preceding the item with that ID will be returned.
   */
  before?: string;
  /**
   * The limit of items to be returned in the list, between 0 and 200. `>= 0` `<= 200`. Default is `10`.
   */
  limit?: number;
  /**
   * The unique identifier for the plan to be filtered by.
   */
  plan?: GigsApi.PlanId;
  /**
   * The unique identifier for the sim to be filtered by.
   */
  sim?: GigsApi.SimId;
  /**
   * A comma-separated list of statuses to filter the subscriptions by. Only pending and active subscriptions are returned by default. Default is `pending` `active`.
   */
  status?: GigsApi.SubscriptionStatus;
  /**
   * The unique identifier for the user to be filtered by.
   */
  user?: string;
}
