/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const Response: core.schemas.Schema<serializers.plans.archive.Response.Raw, GigsApi.Plan> =
  core.schemas.lazyObject(async () => (await import("../..")).Plan);

export declare namespace Response {
  type Raw = serializers.Plan.Raw;
}
