/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsGigsCoreApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const Response: core.schemas.Schema<serializers.plans.list.Response.Raw, GigsGigsCoreApi.PlanList> =
  core.schemas.lazyObject(async () => (await import("../..")).PlanList);

export declare namespace Response {
  type Raw = serializers.PlanList.Raw;
}
