/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CurrentPeriod {
  /** Sequence number of the subscription period. */
  number: number;
  /** Beginning of the current subscription period. */
  start: Date;
  /** End of the current subscription period. */
  end: Date;
}
