/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { GigsApi } from "@fern-api/gigs";

export interface SubscriptionItem {
  /** Type of object is always `subscription`. */
  object: string;
  /** Unique identifier for the subscription. */
  id: GigsApi.SubscriptionId;
  currentPeriod?: GigsApi.CurrentPeriod;
  /** The phone number attached to the SIM in E.164 format. Only available for voice plans. */
  phoneNumber: string;
  plan: string;
  /** Unique identifier for the porting. */
  porting?: string;
  sim: string;
  /** The current status of the subscription. */
  status: GigsApi.SubscriptionStatus;
  user: string;
  /** Time when the subscription was activated. */
  activatedAt: Date;
  /** Time when the subscription was canceled. */
  canceledAt: Date;
  /** Time when the subscription was created. */
  createdAt: Date;
  /** Time when the subscription was ended. */
  endedAt: Date;
  /** Time when the subscription was first used. */
  firstUsageAt: Date;
}
