/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { GigsGigsCoreApi } from "@fern-api/gigs";

export interface Subscription {
  /** Type of object is always `subscription`. */
  object: GigsGigsCoreApi.SubscriptionObject;
  /** Unique identifier for the subscription. */
  id: string;
  currentPeriod?: GigsGigsCoreApi.CurrentPeriod;
  /** The phone number attached to the SIM in E.164 format. Only available for voice plans. */
  phoneNumber: string;
  plan: GigsGigsCoreApi.Plan;
  /** Unique identifier for the porting. */
  porting?: string;
  sim?: GigsGigsCoreApi.Sim;
  /** The current status of the subscription. */
  status: GigsGigsCoreApi.SubscriptionStatus;
  user: GigsGigsCoreApi.User;
  /** Time when the subscription was activated. */
  activatedAt: Date;
  /** Time when the subscription was canceled. */
  canceledAt: Date;
  /** Time when the subscription was created. */
  createdAt: Date;
  /** Time when the subscription was ended. */
  endedAt: Date;
  /** Time when the subscription was first used. */
  firstUsageAt: Date;
}
