/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SubscriptionStatus = "pending" | "active" | "ended";

export const SubscriptionStatus = {
  Pending: "pending",
  Active: "active",
  Ended: "ended",
} as const;
