/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SubscriptionObject = "subscription";

export const SubscriptionObject = {
  Subscription: "subscription",
} as const;
