/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const Response: core.schemas.Schema<serializers.devices.retrieve.Response.Raw, GigsApi.Device> =
  core.schemas.lazyObject(async () => (await import("../..")).Device);

export declare namespace Response {
  type Raw = serializers.Device.Raw;
}
