/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../environments";
import * as core from "../../../core";
import { GigsGigsCoreApi } from "@fern-api/gigs";
import urlJoin from "url-join";
import * as serializers from "../../../serialization";

export declare namespace Client {
  interface Options {
    environment?: environments.Environment | string;
    token?: core.Supplier<core.BearerToken>;
  }
}

export class Client {
  constructor(private readonly options: Client.Options) {}

  public async retrieve(project: GigsGigsCoreApi.ProjectId): Promise<GigsGigsCoreApi.projects.retrieve.Response> {
    const _response = await core.fetcher({
      url: urlJoin(this.options.environment ?? environments.Environment.Production, `/projects/${project}`),
      method: "GET",
      headers: {
        Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
      },
    });
    if (_response.ok) {
      return {
        ok: true,
        body: await serializers.projects.retrieve.Response.parse(
          _response.body as serializers.projects.retrieve.Response.Raw
        ),
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 404:
          return {
            ok: false,
            error: GigsGigsCoreApi.projects.retrieve.Error.doesNotExist(
              await serializers.DoesNotExist.parse(_response.error.body as serializers.DoesNotExist.Raw)
            ),
          };
      }
    }

    return {
      ok: false,
      error: GigsGigsCoreApi.projects.retrieve.Error._unknown(_response.error),
    };
  }
}
