/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { GigsApi } from "@fern-api/gigs";
import * as core from "../../../core";

export type Response = core.APIResponse<GigsApi.Project, GigsApi.projects.retrieve.Error>;
export type Error = GigsApi.projects.retrieve.Error.DoesNotExist | GigsApi.projects.retrieve.Error._Unknown;

export declare namespace Error {
  interface DoesNotExist extends _Utils {
    statusCode: 404;
    content: GigsApi.DoesNotExist;
  }

  interface _Unknown extends _Utils {
    statusCode: void;
    content: core.Fetcher.Error;
  }

  interface _Utils {
    _visit: <_Result>(visitor: GigsApi.projects.retrieve.Error._Visitor<_Result>) => _Result;
  }

  interface _Visitor<_Result> {
    doesNotExist: (value: GigsApi.DoesNotExist) => _Result;
    _other: (value: core.Fetcher.Error) => _Result;
  }
}

export const Error = {
  doesNotExist: (value: GigsApi.DoesNotExist): GigsApi.projects.retrieve.Error.DoesNotExist => {
    const valueWithoutVisit: Omit<GigsApi.projects.retrieve.Error.DoesNotExist, "_visit"> = {
      content: value,
      statusCode: 404,
    };
    return core.addNonEnumerableProperty(valueWithoutVisit, "_visit", function <
      _Result
    >(this: GigsApi.projects.retrieve.Error.DoesNotExist, visitor: GigsApi.projects.retrieve.Error._Visitor<_Result>) {
      return GigsApi.projects.retrieve.Error._visit(this, visitor);
    });
  },

  _unknown: (fetcherError: core.Fetcher.Error): GigsApi.projects.retrieve.Error._Unknown => {
    const valueWithoutVisit = fetcherError as unknown as Omit<GigsApi.projects.retrieve.Error._Unknown, "_visit">;
    return core.addNonEnumerableProperty(valueWithoutVisit, "_visit", function <
      _Result
    >(this: GigsApi.projects.retrieve.Error._Unknown, visitor: GigsApi.projects.retrieve.Error._Visitor<_Result>) {
      return GigsApi.projects.retrieve.Error._visit(this, visitor);
    });
  },

  _visit: <_Result>(
    value: GigsApi.projects.retrieve.Error,
    visitor: GigsApi.projects.retrieve.Error._Visitor<_Result>
  ): _Result => {
    switch (value.statusCode) {
      case 404:
        return visitor.doesNotExist(value.content);
      default:
        return visitor._other(value as any);
    }
  },
} as const;
