/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsGigsCoreApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const CurrentPeriod: core.schemas.ObjectSchema<serializers.CurrentPeriod.Raw, GigsGigsCoreApi.CurrentPeriod> =
  core.schemas.object({
    number: core.schemas.number(),
    start: core.schemas.date(),
    end: core.schemas.date(),
  });

export declare namespace CurrentPeriod {
  interface Raw {
    number: number;
    start: string;
    end: string;
  }
}
