/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsGigsCoreApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const SubscriptionObject: core.schemas.Schema<
  serializers.SubscriptionObject.Raw,
  GigsGigsCoreApi.SubscriptionObject
> = core.schemas.enum_(["subscription"]);

export declare namespace SubscriptionObject {
  type Raw = "subscription";
}
