/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsGigsCoreApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const SubscriptionId: core.schemas.Schema<serializers.SubscriptionId.Raw, GigsGigsCoreApi.SubscriptionId> =
  core.schemas.string();

export declare namespace SubscriptionId {
  type Raw = string;
}
