/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const SubscriptionObject: core.schemas.Schema<serializers.SubscriptionObject.Raw, GigsApi.SubscriptionObject> =
  core.schemas.enum_(["subscription"]);

export declare namespace SubscriptionObject {
  type Raw = "subscription";
}
