/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The legal address for the company that manages the project.
 */
export interface LegalAddress {
  /** The company's legal name. */
  name: string;
  /** The city/municipality of the company's legal address. */
  city: string;
  /** The ISO 3166-1 alpha-2 country code for the company's legal address. */
  country: string;
  /** The first line of the company's legal address, e.g. street and house number. */
  line1: string;
  /** The second line of the given street address, e.g. Apartment number. */
  line2: string;
  /** The postal code of the given street address. */
  postalCode: string;
  /** The state/province/region of the given street address. */
  state: string;
}
