/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { GigsGigsCoreApi } from "@fern-api/gigs";

export interface Organization {
  /** Type of object is always `organization`. */
  object: string;
  /** Unique identifier for the organization. */
  id: GigsGigsCoreApi.OrganizationId;
  /** Name for the organization. */
  name: string;
  /** Time when the organization was created. */
  createdAt: Date;
}
