/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { GigsApi } from "@fern-api/gigs";

/**
 * Configuration parameters for the project use of payments.
 */
export interface Payments {
  /** Three-letter ISO 4217 currency code representing the currency of the project. Must be a supported currency. */
  currency: string;
  /** The mode in which the payments operate. */
  mode: GigsApi.PaymentsMode;
}
