/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { GigsGigsCoreApi } from "@fern-api/gigs";

export interface Project {
  /** Type of object is always `project`. */
  object: string;
  /** Globally unique identifier for the project. */
  id: GigsGigsCoreApi.ProjectId;
  /** Small-resolution project icon with an aspect ratio of 1:1. */
  image?: string;
  /** The legal address for the company that manages the project. */
  legal?: GigsGigsCoreApi.LegalAddress;
  /** List of supported locales represented as IETF language tags, ordered by preference. */
  locales: string[];
  /** A human-readable name for the project. */
  name: string;
  organization: GigsGigsCoreApi.Organization;
  payments: GigsGigsCoreApi.Payments;
  /** Indicates which entity will be registered as the owner of the subscription with the providers. When company is selected the legal address associated with the project will be used for the registration. */
  subscriptionOwner: GigsGigsCoreApi.SubscriptionOwner;
  /** Contact details for consumer support requests regarding the project. */
  support?: GigsGigsCoreApi.Support;
  /** Time when the project was created. */
  createdAt: Date;
}
