/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SubscriptionOwner = "user" | "company";

export const SubscriptionOwner = {
  User: "user",
  Company: "company",
} as const;
