/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Support {
  /** A publicly available email address for consumer support requests regarding the project. */
  email?: string;
  /** A publicly available phone number in E.164 format for consumer support requests regarding the project. */
  phoneNumber?: string;
}
