/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { GigsApi } from "@fern-api/gigs";
import * as core from "../../../core";

export type Response = core.APIResponse<GigsApi.User, GigsApi.users.create.Error>;
export type Error = GigsApi.users.create.Error.InvalidIccid | GigsApi.users.create.Error._Unknown;

export declare namespace Error {
  interface InvalidIccid extends _Utils {
    statusCode: 422;
    content: GigsApi.InvalidIccid;
  }

  interface _Unknown extends _Utils {
    statusCode: void;
    content: core.Fetcher.Error;
  }

  interface _Utils {
    _visit: <_Result>(visitor: GigsApi.users.create.Error._Visitor<_Result>) => _Result;
  }

  interface _Visitor<_Result> {
    invalidIccid: (value: GigsApi.InvalidIccid) => _Result;
    _other: (value: core.Fetcher.Error) => _Result;
  }
}

export const Error = {
  invalidIccid: (value: GigsApi.InvalidIccid): GigsApi.users.create.Error.InvalidIccid => {
    const valueWithoutVisit: Omit<GigsApi.users.create.Error.InvalidIccid, "_visit"> = {
      content: value,
      statusCode: 422,
    };
    return core.addNonEnumerableProperty(valueWithoutVisit, "_visit", function <
      _Result
    >(this: GigsApi.users.create.Error.InvalidIccid, visitor: GigsApi.users.create.Error._Visitor<_Result>) {
      return GigsApi.users.create.Error._visit(this, visitor);
    });
  },

  _unknown: (fetcherError: core.Fetcher.Error): GigsApi.users.create.Error._Unknown => {
    const valueWithoutVisit = fetcherError as unknown as Omit<GigsApi.users.create.Error._Unknown, "_visit">;
    return core.addNonEnumerableProperty(valueWithoutVisit, "_visit", function <
      _Result
    >(this: GigsApi.users.create.Error._Unknown, visitor: GigsApi.users.create.Error._Visitor<_Result>) {
      return GigsApi.users.create.Error._visit(this, visitor);
    });
  },

  _visit: <_Result>(
    value: GigsApi.users.create.Error,
    visitor: GigsApi.users.create.Error._Visitor<_Result>
  ): _Result => {
    switch (value.statusCode) {
      case 422:
        return visitor.invalidIccid(value.content);
      default:
        return visitor._other(value as any);
    }
  },
} as const;
