/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsGigsCoreApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const PaymentsMode: core.schemas.Schema<serializers.PaymentsMode.Raw, GigsGigsCoreApi.PaymentsMode> =
  core.schemas.enum_(["live", "test"]);

export declare namespace PaymentsMode {
  type Raw = "live" | "test";
}
