/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsGigsCoreApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const Payments: core.schemas.ObjectSchema<serializers.Payments.Raw, GigsGigsCoreApi.Payments> =
  core.schemas.object({
    currency: core.schemas.string(),
    mode: core.schemas.lazy(async () => (await import("../..")).PaymentsMode),
  });

export declare namespace Payments {
  interface Raw {
    currency: string;
    mode: serializers.PaymentsMode.Raw;
  }
}
