/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const ProjectId: core.schemas.Schema<serializers.ProjectId.Raw, GigsApi.ProjectId> = core.schemas.string();

export declare namespace ProjectId {
  type Raw = string;
}
