/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const Support: core.schemas.ObjectSchema<serializers.Support.Raw, GigsApi.Support> = core.schemas.object({
  email: core.schemas.string().optional(),
  phoneNumber: core.schemas.string().optional(),
});

export declare namespace Support {
  interface Raw {
    email?: string | null;
    phoneNumber?: string | null;
  }
}
