/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { GigsApi } from "@fern-api/gigs";

export interface Sim {
  object: GigsApi.SimObject;
  /** Unique identifier for the SIM. */
  id: string;
  /** The ICCID (integrated circuit card identifier) associated with the SIM. */
  iccid: string;
  /** The ID of the network provider of the SIM. */
  provider: string;
  /** The status of the SIM. */
  status: GigsApi.SimStatus;
  /** The type of the SIM. */
  type: GigsApi.SimTypes;
  /** Time when the SIM was created. */
  createdAt: Date;
}
