/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SimStatus = "inactive" | "active" | "retired";

export const SimStatus = {
  Inactive: "inactive",
  Active: "active",
  Retired: "retired",
} as const;
