/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { GigsGigsCoreApi } from "@fern-api/gigs";
import * as core from "../../../core";

export type Response = core.APIResponse<GigsGigsCoreApi.Device, GigsGigsCoreApi.devices.retrieve.Error>;
export type Error =
  | GigsGigsCoreApi.devices.retrieve.Error.DoesNotExist
  | GigsGigsCoreApi.devices.retrieve.Error._Unknown;

export declare namespace Error {
  interface DoesNotExist extends _Utils {
    statusCode: 404;
    content: GigsGigsCoreApi.DoesNotExist;
  }

  interface _Unknown extends _Utils {
    statusCode: void;
    content: core.Fetcher.Error;
  }

  interface _Utils {
    _visit: <_Result>(visitor: GigsGigsCoreApi.devices.retrieve.Error._Visitor<_Result>) => _Result;
  }

  interface _Visitor<_Result> {
    doesNotExist: (value: GigsGigsCoreApi.DoesNotExist) => _Result;
    _other: (value: core.Fetcher.Error) => _Result;
  }
}

export const Error = {
  doesNotExist: (value: GigsGigsCoreApi.DoesNotExist): GigsGigsCoreApi.devices.retrieve.Error.DoesNotExist => {
    const valueWithoutVisit: Omit<GigsGigsCoreApi.devices.retrieve.Error.DoesNotExist, "_visit"> = {
      content: value,
      statusCode: 404,
    };
    return core.addNonEnumerableProperty(valueWithoutVisit, "_visit", function <
      _Result
    >(this: GigsGigsCoreApi.devices.retrieve.Error.DoesNotExist, visitor: GigsGigsCoreApi.devices.retrieve.Error._Visitor<_Result>) {
      return GigsGigsCoreApi.devices.retrieve.Error._visit(this, visitor);
    });
  },

  _unknown: (fetcherError: core.Fetcher.Error): GigsGigsCoreApi.devices.retrieve.Error._Unknown => {
    const valueWithoutVisit = fetcherError as unknown as Omit<
      GigsGigsCoreApi.devices.retrieve.Error._Unknown,
      "_visit"
    >;
    return core.addNonEnumerableProperty(valueWithoutVisit, "_visit", function <
      _Result
    >(this: GigsGigsCoreApi.devices.retrieve.Error._Unknown, visitor: GigsGigsCoreApi.devices.retrieve.Error._Visitor<_Result>) {
      return GigsGigsCoreApi.devices.retrieve.Error._visit(this, visitor);
    });
  },

  _visit: <_Result>(
    value: GigsGigsCoreApi.devices.retrieve.Error,
    visitor: GigsGigsCoreApi.devices.retrieve.Error._Visitor<_Result>
  ): _Result => {
    switch (value.statusCode) {
      case 404:
        return visitor.doesNotExist(value.content);
      default:
        return visitor._other(value as any);
    }
  },
} as const;
