/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsGigsCoreApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const DoesNotExist: core.schemas.Schema<serializers.DoesNotExist.Raw, GigsGigsCoreApi.DoesNotExist> =
  core.schemas.lazyObject(async () => (await import("../..")).DoesNotExistBody);

export declare namespace DoesNotExist {
  type Raw = serializers.DoesNotExistBody.Raw;
}
