/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const InvalidIccid: core.schemas.Schema<serializers.InvalidIccid.Raw, GigsApi.InvalidIccid> =
  core.schemas.lazyObject(async () => (await import("../..")).InvalidIccidBody);

export declare namespace InvalidIccid {
  type Raw = serializers.InvalidIccidBody.Raw;
}
