/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsGigsCoreApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const Response: core.schemas.Schema<serializers.projects.retrieve.Response.Raw, GigsGigsCoreApi.Project> =
  core.schemas.lazyObject(async () => (await import("../..")).Project);

export declare namespace Response {
  type Raw = serializers.Project.Raw;
}
