/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GigsGigsCoreApi } from "@fern-api/gigs";
import * as core from "../../../core";

export const Response: core.schemas.Schema<
  serializers.subscriptions.listAll.Response.Raw,
  GigsGigsCoreApi.SubscriptionList
> = core.schemas.lazyObject(async () => (await import("../..")).SubscriptionList);

export declare namespace Response {
  type Raw = serializers.SubscriptionList.Raw;
}
