/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { GigsGigsCoreApi } from "@fern-api/gigs";

export interface Device {
  /** Type of object is always `deviceModel`. */
  object: GigsGigsCoreApi.DeviceModelObject;
  /** Unique identifier for the deviceModel. */
  id: GigsGigsCoreApi.DeviceId;
  /** The brand of the device model. */
  brand: string;
  /** The device model's name. */
  name: string;
  /** List of SIM types supported by this device model. */
  simTypes: GigsGigsCoreApi.SimTypes[];
  /** The type of the device model. */
  type: GigsGigsCoreApi.DeviceModelType;
}
