/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type DeviceModelType =
  | "car"
  | "iot"
  | "laptop"
  | "router"
  | "smartphone"
  | "feature_phone"
  | "smartwatch"
  | "tablet"
  | "wearable"
  | "other";

export const DeviceModelType = {
  Car: "car",
  Iot: "iot",
  Laptop: "laptop",
  Router: "router",
  Smartphone: "smartphone",
  Featurephone: "feature_phone",
  Smartwatch: "smartwatch",
  Tablet: "tablet",
  Wearable: "wearable",
  Other: "other",
} as const;
