/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { GigsGigsCoreApi } from "@fern-api/gigs";

export interface User {
  /** Type of object is always `user`. */
  object: GigsGigsCoreApi.UserObject;
  /** Unique identifier for the user. */
  id: string;
  /** The birthday of the user. */
  birthday: string;
  /** The primary verified email address of the user. */
  email: string;
  /** Whether the user's primary email address is verified or not. */
  emailVerified: boolean;
  /** The user's full name. Some plans require the user name to be present when creating a subscription. Check the plan requirements for that. */
  fullName: string;
  /** The user's locale preference represented as an [IETF language tag](https://en.wikipedia.org/wiki/IETF_language_tag). It defaults to the project's preferred locale. */
  preferredLocale: string;
  /** Time when the user was created. */
  createdAt: Date;
}
